# Generated by Django 3.1.6 on 2021-07-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('SI_No', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=200)),
                ('Parent_ID', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['SI_No'],
            },
        ),
    ]
