# Generated by Django 3.1.6 on 2021-07-06 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210706_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='create_time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
